### ISSUE TITLE
SQL model - Project prototype

### ISSUE THREAD

**Issue by tabaqui10** [MrAbdelaziz/GestionStock-django#2]
@MrAbdelaziz  @ynsl31 

Hello !

I downloaded your project and I had to change this instruction "from django.urls import url" to "from django.urls import re_path" because the "url" function is no longer supported by Django (+4.0) but that's not my issue, it's working with re_path().

The thing is that it is necessary to install Mysql and to create a datababe named "gestionstockdjango" to run the server, so I made a database with Mysql but it's empty and when I try to connect with a username and a password through the http://127.0.0.1:8000/ adress I get errors because tables are missing. 

In the pictures of your project I see that you have a functionning model so I guess you have a complete working SQL database.
Can I ask you to send it to me please ? It would really help me to have a solid basis to understand how everything works.

my email adress is: playergeekk@gmail.com 

Best regards

**Comment by MrAbdelaziz** [comment]
Hello,

Thank you for reaching out to me. However, I must clarify that the database used in the project is actually SQLite3 and not MySQL. The database is included in the project folder as a file named "db.sqlite3".

To run the project, you do not need to install MySQL . Instead, you can simply use the included SQLite3 database.

good luck !

**Comment by MrAbdelaziz** [comment]
Hello @tabaqui10 !

I'm glad to hear that you were able to make the necessary changes to get the project to work with Django +4.0 using re_path().

Regarding the database, the project is based on Django Rest Framework, which means that it uses Django's built-in ORM (Object Relational Mapper) to interact with the database. The ORM is responsible for creating the necessary tables in the database based on the models defined in the project.

To create the necessary tables in the database, you need to run the following command in your terminal:

```
python manage.py migrate
```


This command will create the necessary tables in your database based on the models defined in the project. You should run this command after creating your database and before running the server.

Please note that if you have made any changes to the models in the project, you will need to run the following command to create and apply the necessary migrations:

```
python manage.py makemigrations
python manage.py migrate
```
PS : Project models stored at [GestionStock-django](https://github.com/MrAbdelaziz/GestionStock-django/tree/8045aead79ffd6fd7e38f3b5cd5c9153dda65eaf/API)

I hope this helps!

Best regards.
Abdelaziz
